name: update data
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Wiki scrape
        run: node index.js
        
      - name: Upload csv data
        uses: actions/upload-artifact@v3
        with:
          name: songlist
          path: 20220514_data.csv

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download csv data
        uses: actions/download-artifact@v3
        with:
          name: songlist

      - name: Setup Python
        uses: actions/setup-python@v3
      
      - name: pip install
        run: |
          pip install matplotlib
          pip install pillow
      
      - name: get fig on TODAY
        run: python difficulty_stats_calc.py `date +%Y/%m/%d`
      
      - run: ls -l
