name: update data
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - run: ls -l
      
      - name: Wiki scrape
        run: node index.js
        
      - run: |
          ls -l
          cat 20220514_data.csv
