name: update data
on: 
  workflow_dispatch:
  schedule:
    - cron: '45 20 * * *'

jobs:
  job1:
    name: web scraping
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Wiki scrape
        run: node index.js

      - name: Upload csv
        uses: actions/upload-artifact@v3
        with:
          name: songlist
          path: 20220514_data.csv

  job2:
    name: create image
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Download csv
        uses: actions/download-artifact@v3
        with:
          name: songlist

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Other setups
        run: |
          sudo apt-get update
          sudo apt-get install fonts-ipaexfont
          pip install matplotlib
          pip install pillow
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ secrets.MY_EMAIL }}

      - name: "##### main run #####"
        run: |
          python difficulty_stats_calc.py `date +%Y/%m/01`
          
          ls ./docs/figs/latest/.
          echo
          echo
          ls ./docs/figs/latest
          echo
          echo \
          
          if [[ $(find ./docs/figs/latest \*.png | wc -w) -ne 1 ]]; then
          echo "only one latest file is allowed"
          exit 1
          fi
          
          if [[ ! $(find ./docs/figs \*.png -type f) =~ $(find ./docs/figs/latest \*.png) ]]; then
          mv ./docs/figs/latest/* ./docs/figs/
          fi
          
          rm -f /docs/figs/latest/*
          python difficulty_stats_calc.py `date +%Y/%m/%d`
          

      - name: Upload png(s)
        uses: actions/upload-artifact@v3
        with:
          name: madskillz_req
          path: ./docs/figs

#     this git push tends to be time-consuming and affects checkout in next job
#       - name: Push figs folder (if needed)
#         if: false
#         run: |
#           git add ./docs/figs/. \
#           && git diff --exit-code --staged --merge-base \
#           || (git commit -m "auto commit figs folder" \
#           && git push)
          
  job3:
    name: create html
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
      
      - name: Download figs
        uses: actions/download-artifact@v3
        with:
          name: madskillz_req
          path: ./docs/figs
          
      - name: Other setups
        run: |
          ls -la ./docs/figs
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ secrets.MY_EMAIL }}
      
      - name: Create html
        run: |
          npm run make_js
      
      - name: Push docs (if needed)
        run: |
          git add ./docs/. -N \
          && git diff --exit-code \
          || (git add ./docs/. \
          && git commit -m "auto commit docs folder" \
          && git push)
          
      
